version: "3.9"

services:
  app:
    build: .
    container_name: contest-system-app
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - backend

  mongo:
    image: mongo:6
    container_name: contest-system-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

networks:
  backend:

volumes:
  mongo_data:
